### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE error

### ISSUE THREAD

**Issue by redconfetti** [sudomesh/makenode#14]
Freshly flashed a Western Digital My Net N600 router with the Chaos Calmer build. I'm using Node v0.10.25

```
$ ./makenode.js 
Connecting to node at 172.22.0.1 using ssh on port 22
Detecting node hardware capabilities
Version string = OpenWRT 15.05 (Chaos Calmer)
cleaning /home/redconfetti/Projects/mesh/makenode/staging
cleaning /home/redconfetti/Projects/mesh/makenode/templateStaging
Generating SSH keys
stage
Error: Error creating node in remote node database: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
```

**Comment by redconfetti** [comment]
@Juul just noted that this just requires an update to the [LetsEncrypt](https://letsencrypt.org/) certificate.

**Comment by redconfetti** [comment]
Work around, for now just checkout the `unstrictssl` branch.

```
$ git checkout unstrictssl
```

**Comment by redconfetti** [comment]
Note, if setting up My Net N600 by Western Digital, you will be prompted to enter the transmit power, use `23`. @Juul said it should be the same for the other routers also.

```
Enter wifi transmit power in dBm: 23
```

**Comment by blueskymonster** [comment]
I'm currently trying to set up my N600 node. I ran into a similar issue as you @redconfetti. This was my output:
```
Akaimos:makenode elliot$ ./makenode.js
Connecting to node at 172.22.0.1 using ssh on port 22
Detecting node hardware capabilities
Version string = OpenWRT 15.05 (Chaos Calmer)
cleaning /Users/elliot/src/mesh/makenode/staging
cleaning /Users/elliot/src/mesh/makenode/templateStaging
Generating SSH keys
stage
Error: Error creating node in remote node database: Error: unable to verify the first certificate
```

I then tried checking out the `unstrictssl` branch, running `npm install` again and trying again with this result:
```
Akaimos:makenode elliot$ ./makenode.js
Connecting to node at 172.22.0.1 using ssh on port 22
Detecting node hardware capabilities
Version string = OpenWRT 15.05 (Chaos Calmer)
cleaning /Users/elliot/src/mesh/makenode/staging
cleaning /Users/elliot/src/mesh/makenode/templateStaging
Generating SSH keys
stage
Error: Error creating node in remote node database: Invalid JSON returned from server: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>
```
Pretty odd that I'm getting an HTTP response for a JSON request. It makes me think that I'm doing something stupid here. Is my N600 supposed to be plugged into internet for this step?

**Comment by willmartindotcom** [comment]
I'm having this same problem with an N600. Here's the error:

linux@linux:~/makenode$  ./makenode.js
Connecting to node at 172.22.0.1 using ssh on port 22
Detecting node hardware capabilities
Version string = OpenWRT 15.05 (Chaos Calmer)
cleaning /home/linux/makenode/staging
cleaning /home/linux/makenode/templateStaging
Generating SSH keys
stage
Error: Error creating node in remote node database: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

**Comment by max-b** [comment]
The meshnode database is down. I don't administrate that, so you're gonna need to get in touch with @Juul.

**Comment by Juul** [comment]
Our server had been shut down by the provider and not turned back on. It's back on now.

I also switched to a startssl certificate. Hopefully that gets rid of the UNABLE_TO_VERIFY_LEAF_SIGNATURE error. Let me know!

**Comment by willmartindotcom** [comment]
Now i'm getting a different error:

linux@linux:~/makenode$  ./makenode.js
Connecting to node at 172.22.0.1 using ssh on port 22
Detecting node hardware capabilities
Version string = OpenWRT 15.05 (Chaos Calmer)
cleaning /home/linux/makenode/staging
cleaning /home/linux/makenode/templateStaging
Generating SSH keys
stage
Error: Error creating node in remote node database: Error: getaddrinfo EADDRINFO

**Comment by willmartindotcom** [comment]
nevermind - I just had to unplug the ethernet and plug it back in - it works now!
