### ISSUE TITLE
Question: What is the "... fast" network?

### ISSUE THREAD

**Issue by gobengo** [sudomesh/makenode#20]
I set up a home node, now I have at least these SSIDs:
* peoplesopen.net fast 65.30.193
* peoplesopen.net 65.30.193

What is the 'fast' one for?

I can see that /etc/config/wireless contains:
```
# the open wifi ap 
config wifi-iface
  option device 'radio0'
  option ifname 'open2'
  option encryption 'none'
  option network 'open'
  option mode 'ap'
  option ssid 'peoplesopen.net 65.30.193'

# ...

# the open wifi ap on 5 ghz                                                
config wifi-iface                                                          
  option device 'radio1'                                                   
  option ifname 'open5'                                                    
  option encryption 'none'                                                 
  option network 'open'                                                    
  option mode 'ap'                                                         
  option ssid 'peoplesopen.net fast 65.30.193'

```

Looks like the 'fast' one uses the 5 Ghz radio? Is that the main difference? Do you think replacing 'fast' with '5Ghz' would be more accurate?

/cc @gmoran6 who is operating this home node with me

**Comment by jhpoelen** [comment]
yep "fast" corresponds to 5GHz radio via interface open5 . I believe the idea of using "fast" was to make the choice a little easier for folks that don't know what 5GHz means.

**Comment by gobengo** [comment]
fair enough. Sometime I'll see if I can make the 5Ghz SSID template easily configurable so I can change it if I want, but have current default.
