### ISSUE TITLE
Check if opkg can be put in atheros and ar71xx folders without specifying spectrum

### ISSUE THREAD

**Issue by max-b** [sudomesh/makenode#5]
We currently have these files:
 configs/ar71xx/2.4ghz/templates/files/etc/opkg.conf
 configs/ar71xx/5ghz/templates/files/etc/opkg.conf
 configs/atheros/2.4ghz/templates/files/etc/opkg.conf

Ideally, we'd have just these two:
 configs/ar71xx/templates/files/etc/opkg.conf
 configs/atheros/templates/files/etc/opkg.conf

**Comment by Juul** [comment]
On Sun, Feb 8, 2015 at 3:57 PM, max-b <notifications@github.com> wrote:

> We currently have these files:
> configs/ar71xx/2.4ghz/templates/files/etc/opkg.conf
> configs/ar71xx/5ghz/templates/files/etc/opkg.conf
> configs/atheros/2.4ghz/templates/files/etc/opkg.conf
>
> Ideally, we'd have just these two:
> configs/ar71xx/templates/files/etc/opkg.conf
> configs/atheros/templates/files/etc/opkg.conf
>

That should work. Unless I fucked something up :)

-- 
marc/juul

**Comment by max-b** [comment]
Yup works fine
