### ISSUE TITLE
Run babel on both 2.4 and 5 ghz radios on dual-radio nodes

### ISSUE THREAD

**Issue by Juul** [sudomesh/makenode#9]
Right now we are only running babel on the 5 ghz radios. Imagine running babel on both 2.4 and 5 ghz radios on Node A that is connected to Node B with both 2.4 and 5 ghz radios. There are some walls in between so the 2.4 GHz connection is better (higher bandwidth, lower packet loss) than the 5 GHz connection. The  client sends data bond for Node B. The correct choice is for babel to route the data over the 5 ghz connection, but as far as I know (and I may be wrong) there is nothing in babel that does this. 

Then there is the problem that each radio needs its own IP for babel to even acknowledge them as separate links (since it indexes links by IP): https://tools.ietf.org/html/rfc6126 section 3.2.3 (bottom paragraph). This shouldn't be a huge problem. We can just assign the .1 to the 2.4 ghz interface and .2 to the 5 ghz and it probably won't change our routing rules too much since the private and open networks will still only be on 2.4 ghz.

As max pointed out we have a bad situation right now since 2.4 ghz is somewhat better at making non-line-of-sight connections than 5 ghz, so we may have nodes that can see each-other on 2.4 ghz but not on 5 ghz and they're not talking to each-other because we're not running babel on 2.4.

**Comment by Juul** [comment]
Since we are also adding "radios" to indoor nodes by connecting nanostations/nanobridges we'd want to figure out how to treat these as radios as well, telling babel which nodes are on which frequencies.

**Comment by mitar** [comment]
I think this talk could be useful: https://www.youtube.com/watch?v=1VNzm0shSA8

**Comment by max-b** [comment]
https://tools.ietf.org/html/draft-chroboczek-babel-diversity-routing-00

Looks like it's set to use the diversity routing by default. Fancy....

**Comment by max-b** [comment]
We have totally got this covered :)
